Proceso:

● Transformación y limpieza de los datos

● Análisis descriptivo de los datos

● Visualización de los datos

● Informe explicativo del análisis

In [1]:
import pandas as pd

#para que aparezcan todas las columnas
pd.set_option('display.max_columns', None)

import numpy as np

In [22]:
datos_clientes_original=pd.read_excel('customer-details.xlsx', index_col=0)
datos_clientes_original.sample(5)

Income  Kidhome  Teenhome Dt_Customer  NumWebVisitsMonth  \
12838  123287        1         2  2012-04-12                  3   
3755    54507        1         1  2012-01-25                  5   
2539    18631        1         1  2012-05-01                 12   
987    156877        1         0  2012-05-13                 21   
15071  102898        1         0  2012-03-31                 14   

                                         ID  
12838  f572f3bf-c44c-4dc0-a839-1781f472cc2a  
3755   21317657-5f14-45d0-8c4d-819c7843c5dc  
2539   87755586-c83c-4c33-ba63-e59340872239  
987    e61866fd-5a08-47d7-8881-38799a08b602  
15071  356a2da0-55ad-44e1-8047-81e20ef95ba1

In [10]:
#da error al importar el excel.
# Error: ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
#Utilizado pip install openpyxl en otro archivo, desde este daba SyntaxError: invalid syntax

In [19]:
#Hacemos copia del documento original
datos_clientes=datos_clientes_original.copy()

In [21]:
#para ver las filas (registros) con sus columnas. Incluye las tres hojas juntas?. Hoja 2012 con 20114 registros 
datos_clientes.shape

(20115, 6)

In [ ]:
#Como solo incluye la primera hoja del excel,
#importamos las 3 concatenadas al comprobar que las 3 tienen las mismas columnas
#columnas de indice repetidas al cargar, modificamos con index:col=0
datos_clientes_original_todas_hojas=pd.read_excel('customer-details.xlsx',sheet_name=None, index_col=0)
#unirlas todas en el mismo dataframe
datos_clientes_original_todas_hojas= pd.concat(datos_clientes_original_todas_hojas.values(), ignore_index=True)
#ver ejemplo
datos_clientes_original_todas_hojas.sample(5)

Income  Kidhome  Teenhome Dt_Customer  NumWebVisitsMonth  \
34210  140989        2         2  2014-10-04                  3   
5473   112646        1         2  2012-07-04                 28   
3456    82411        1         2  2012-04-17                  4   
13301   89497        0         1  2012-06-29                 28   
11258  155503        1         1  2012-02-08                 20   

                                         ID  
34210  2565689a-0713-44bf-ab62-696121e91889  
5473   d68b7fb5-ebfe-4f3b-bbc0-92a129f70d70  
3456   1a578f8b-5022-49e1-a99c-94aa17cc3ed4  
13301  630e9a41-c9e2-4c2a-a5cd-f09559fc6e00  
11258  4603624e-40b0-4f4a-8cf7-d34d2850833c

In [40]:
#copia del original en bruto con todas las hojas de años unidos:
datos_clientes= datos_clientes_original_todas_hojas.copy()
datos_clientes.sample(5)

Income  Kidhome  Teenhome Dt_Customer  NumWebVisitsMonth  \
41468   16813        2         1  2014-03-25                 21   
42750   67077        2         2  2014-05-18                 18   
19116  155794        2         0  2012-12-12                 14   
25587  131593        1         1  2013-03-08                 21   
41972  138570        2         0  2014-01-23                 21   

                                         ID  
41468  17e9cc8c-05dc-4e88-9a2a-720400ff04ea  
42750  f4ef7a48-0bdb-4e13-b289-2dd6db151ae1  
19116  94f46a2c-2506-48e5-9455-089c1bf31faa  
25587  86660fc5-3171-497c-84c1-21c44813894e  
41972  7928fa70-390b-4cf6-a1f8-9422cd29a14d

### Limpieza datos clientes:

-Todas las columnas tienen ya el tipo de dato correcto, incluyendo el formato fecha datetime, no es necesario realizar modificaciones.

-Ninguna columna tiene datos nulos

-No hay datos duplicados

-Cambiar titulo de columnas a minusculas para que coincida con la hoja de datos bancarios y hacer mas sencillo el código, ahora está en tipo title

In [ ]:
#para ver las filas (registros) con sus columnas.
#registros coinciden con la suma de las tres hojas individuales en excel
datos_clientes.shape

(43170, 6)

In [42]:
#para ver numero de columnas, ver si el tipo de dato coincide:
datos_clientes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43170 entries, 0 to 43169
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype         
---  ------             --------------  -----         
 0   Income             43170 non-null  int64         
 1   Kidhome            43170 non-null  int64         
 2   Teenhome           43170 non-null  int64         
 3   Dt_Customer        43170 non-null  datetime64[ns]
 4   NumWebVisitsMonth  43170 non-null  int64         
 5   ID                 43170 non-null  object        
dtypes: datetime64[ns](1), int64(4), object(1)
memory usage: 2.0+ MB


In [ ]:
#para ver los nulos que pueda haber, de forma más fiable que con info:
#no es necesario calcular porcentaje de datos totales al dar 0

datos_clientes.isnull().sum()

Income               0
Kidhome              0
Teenhome             0
Dt_Customer          0
NumWebVisitsMonth    0
ID                   0
dtype: int64

In [44]:
#Comprobamos si hay duplicados

datos_clientes.duplicated().sum()

np.int64(0)

In [45]:
#estadisticas principales:
datos_clientes.describe().T

count                           mean  \
Income             43170.0                   93227.389622   
Kidhome            43170.0                       1.004749   
Teenhome           43170.0                       0.998633   
Dt_Customer          43170  2013-05-11 22:09:47.407922176   
NumWebVisitsMonth  43170.0                       16.59129   

                                   min                  25%  \
Income                          5841.0              49608.0   
Kidhome                            0.0                  0.0   
Teenhome                           0.0                  0.0   
Dt_Customer        2012-01-01 00:00:00  2012-07-16 00:00:00   
NumWebVisitsMonth                  1.0                  9.0   

                                   50%                  75%  \
Income                         93009.5             136740.5   
Kidhome                            1.0                  2.0   
Teenhome                           1.0                  2.0   
Dt_Customer        2013-03-01 00:00:00  2014-03-28 00:00:00   
NumWebVisitsMonth                 17.0                 25.0   

                                   max           std  
Income                        180802.0  50498.181989  
Kidhome                            2.0      0.815996  
Teenhome                           2.0      0.816008  
Dt_Customer        2014-12-31 00:00:00           NaN  
NumWebVisitsMonth                 32.0      9.241769

### Primeras conclusiones de estadísticas principales
- **income**: media 96.2k anual. Mínimo 5.8k y máximo 180.8k
-  **kidhome** :media de un niño, minimos sin niños, maximas de dos.
-  **teenhome**: media de 1 dolescente, minimos sin adolescentes, maximas de dos.
-  **numwebvisitsmonth**: media de 16 visitas mensuales, minimo de 1, maximo de 32.

In [49]:
#datos unicos para datos tipo integer, comprobamos si hay numeros que no tengan sentido logico(ej: numero de hijos: 33)
datos_clientes['Kidhome'].unique()

array([1, 0, 2])

In [50]:
datos_clientes['Teenhome'].unique()

array([0, 1, 2])

In [51]:
datos_clientes['NumWebVisitsMonth'].unique()

array([29,  7,  5, 20, 26,  3, 21, 18,  9, 30, 32, 27, 15, 28,  2, 17, 12,
        1, 25, 10, 14, 24, 13, 11,  8, 23, 16,  4, 31, 19, 22,  6])

In [54]:
#cambiar titulos de columnas a lower, similar a datos bancarios:
datos_clientes.columns = datos_clientes.columns.str.lower()
datos_clientes.sample(5)

income  kidhome  teenhome dt_customer  numwebvisitsmonth  \
5557   101553        1         0  2012-08-19                  2   
41670  125564        1         0  2014-02-04                 11   
34366   40735        2         1  2014-09-25                 13   
18678  122815        0         0  2012-07-28                 18   
17755  145876        1         2  2012-08-25                 17   

                                         id  
5557   fd5dc8bf-7441-4394-9fbe-6c4d21521703  
41670  56f22113-ea05-45f4-b8e0-d119d85844f0  
34366  414089fe-1283-4cba-aeff-531cffe752d9  
18678  4e886e0f-a4f0-421d-8597-cd3b0173c160  
17755  f5b6b871-5a58-401f-b7e8-397db7043fdf

### Guardar el archivo limpio

In [57]:
# guardado tanto en csv como el otro archivo de datos bancarios como en excel, similar al original
#error por falta de permisos, codigo similar a datos bancarios para poder guardarlo

In [58]:
#importado para poder guardar en C
import os

In [59]:
#codigo para para poder crear el documento en C
os.makedirs("output", exist_ok=True)
datos_clientes.to_csv("output/customer_details_limpio.csv", index=False)
datos_clientes.to_excel("output/customer_details_limpio.xlsx", index=False)